stages:
  - build
  - deploy

build:
  image: node:latest
  stage: build
  
  variables: 
    PUBLIC_URL: https://daniil_khlyvniuk.gitlab.io/whack-a-mole-react/
  script:
    - npm i     
    - npm run build
  artifacts:
    paths:
      - build/  

pages:
  image: alpine:latest
  stage: deploy

  variables:
    GIT_STRATEGY: none        
  script:
    - mv build public         
  artifacts:
    paths:
      - public
