stages:
  - build
  - deploy

build:
  image: node
  stage: build
  
  variables: 
    PUBLIC_URL: https://daniil_khlyvniuk.gitlab.io/whack-a-mole-react/
  script:
    - npm install     
    - npm build
  artifacts:
    paths:
      - build/  
      - node_modules/

pages:
  image: alpine
  stage: deploy

  variables:
    GIT_STRATEGY: none        
  script:
    - mv build public         
  artifacts:
    paths:
      - public
