stages:
  - build

build:
  image: node:latest   
  stage: build

  variables: 
    PUBLIC_URL: https://jsramblings.gitlab.io/coffee-corner/  
  script:
    - npm install     
    - npm run build
  artifacts:
    paths:
      - build/ 
